os: linux
dist: xenial
sudo: false
language: python
python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7"
 - "pypy"
 - "pypy3"
install:
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install --editable .
script: py.test
after_success:
  - coveralls
cache: pip
