language: python
python:
 - "2.7"
 - "3.3"
 - "3.5"
 - "3.6"
install:
 - pip install -r requirements.txt
 - pip install --editable .
script: py.test
services:
 - memcached
 - redis-server
after_success:
  - coveralls
cache: pip
