language: python
python:
 - "2.7"
 - "3.3"
 - "3.5"
install:
 - pip install -r requirements.txt --use-mirrors
 - pip install --editable .
script: nosetests --with-coverage --cover-package=flask_caching
services:
 - memcached
 - redis-server
after_success:
  - coveralls
